/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "phhqsqktcweqcyedhwbf"

// Clé anon publique Supabase - destinée à être exposée côté client.
// Elle ne donne accès qu'aux opérations autorisées par les Row Level Security (RLS) policies.
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBoaHFzcWt0Y3dlcWN5ZWRod2JmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NjIwMDA4MzUsImV4cCI6MjA3NzU3NjgzNX0.aTnYCzy7S8IH9JyTdS22j7EmUd1qWCBKo-8j6dK_r3o"